version: '2'
services:
  discourse:
    image: vanessa/discourse
    container_name: discourse
    ports:
      - "80:80"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    env_file:
      - .env

  sidekiq:
    image: vanessa/discourse
    container_name: sidekiq
    command: sidekiq -c 3 -v # bundle exec sidekiq
    depends_on:
      - discourse
    links:
      - postgres
      - redis
    env_file:
      - .env
  
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_USER=discourse
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:2.8
